### ISSUE TITLE
Equipment search should include type

### ISSUE THREAD

**Issue by smrgeoinfo** [iedadata/EarthChem-Administrative-Interface#1]
The search box for equipment should allow search by type. E.g. if you type in 'ship' you see a list of all the ships, 'ROV' and should see list of all remote operated vehicles.

**Comment by jasonash** [comment]
Fixed with commit 076879091b8aa4f05a65f65346c7879f9b66e2d3

See:
http://admin.earthchemportal.org/REST/equipment?query=ship
http://admin.earthchemportal.org/REST/equipment?query=AUV
http://admin.earthchemportal.org/REST/equipment?query=HOV
http://admin.earthchemportal.org/REST/equipment?query=ROV
